import { asp , ybi , animeImage , promptnestImg , flavourful, editmagicai} from "../assets/images";
import {
    car,
    contact,
    css,
    estate,
    express,
    git,
    github,
    html,
    javascript,
    linkedin,
    mongodb,
    motion,
    mui,
    nextjs,
    nodejs,
    animeXplorer,
    react,
    redux,
    sass,
    snapgram,
    summiz,
    tailwindcss,
    threads,
    typescript,
    codedamn,
    promptnest,
    editmagicicon,
} from "../assets/icons";

export const skills = [
    {
        imageUrl: css,
        name: "CSS",
        type: "Frontend",
    },
    {
        imageUrl: express,
        name: "Express",
        type: "Backend",
    },
    {
        imageUrl: git,
        name: "Git",
        type: "Version Control",
    },
    {
        imageUrl: github,
        name: "GitHub",
        type: "Version Control",
    },
    {
        imageUrl: html,
        name: "HTML",
        type: "Frontend",
    },
    {
        imageUrl: javascript,
        name: "JavaScript",
        type: "Frontend",
    },
    {
        imageUrl: mongodb,
        name: "MongoDB",
        type: "Database",
    },
    // {
    //     imageUrl: motion,
    //     name: "Motion",
    //     type: "Animation",
    // },
    // {
    //     imageUrl: mui,
    //     name: "Material-UI",
    //     type: "Frontend",
    // },
    {
        imageUrl: nextjs,
        name: "Next.js",
        type: "Frontend",
    },
    {
        imageUrl: nodejs,
        name: "Node.js",
        type: "Backend",
    },
    {
        imageUrl: react,
        name: "React",
        type: "Frontend",
    },
    {
        imageUrl: redux,
        name: "Redux",
        type: "State Management",
    },
    {
        imageUrl: sass,
        name: "Sass",
        type: "Frontend",
    },
    {
        imageUrl: tailwindcss,
        name: "Tailwind CSS",
        type: "Frontend",
    },
    {
        imageUrl: typescript,
        name: "TypeScript",
        type: "Frontend",
    }
];

export const experiences = [
    {
        title: "Software Engineer",
        company_name: "ASP OL MEDIA",
        icon: asp,
        iconBg: "#accbe1",
        date: "March 2022 - Jul 2023",
        points: [
            "Developing and maintaining web email servers and other related technologies.",
            "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
            "Implementing responsive design and ensuring cross-browser compatibility.",
            "Participating in code reviews and providing constructive feedback to other developers.",
        ],
    },
    {
        title: "Big Data and Cloud Computing Internship",
        company_name: "YBI Foundation",
        icon: ybi,
        iconBg: "#fbc3bc",
        date: "Jul 2023 - Aug 2023",
        points: [
            "Big Data Expertise: I have developed proficiency in Apache Spark for processing large datasets and have a strong background in Machine Learning, allowing me to create predictive models. My skills in Statistical and Quantitative Analysis enable me to interpret data and derive insights, using Python for its powerful data analysis capabilities.",
            "Cloud Computing Skills: My experience with Databricks allows me to unify data science and engineering on a single platform, and I'm knowledgeable in Google Cloud Platform for building, deploying, and scaling applications with Google's technology.",
            "Serverless Architecture Proficiency: I am adept at creating serverless architectures, enabling me to build and run applications efficiently without the need to manage servers.",
            "Cloud Migration and Deployment: I possess skills in cloud migration and deployment, ensuring a seamless transition of systems onto the cloud.",
        ],
    },
    // {
    //     title: "React.js Developer",
    //     company_name: "Starbucks",
    //     icon: starbucks,
    //     iconBg: "#accbe1",
    //     date: "March 2020 - April 2021",
    //     points: [
    //         "Developing and maintaining web applications using React.js and other related technologies.",
    //         "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
    //         "Implementing responsive design and ensuring cross-browser compatibility.",
    //         "Participating in code reviews and providing constructive feedback to other developers.",
    //     ],
    // },
    // {
    //     title: "React Native Developer",
    //     company_name: "Tesla",
    //     icon: tesla,
    //     iconBg: "#fbc3bc",
    //     date: "Jan 2021 - Feb 2022",
    //     points: [
    //         "Developing and maintaining web applications using React.js and other related technologies.",
    //         "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
    //         "Implementing responsive design and ensuring cross-browser compatibility.",
    //         "Participating in code reviews and providing constructive feedback to other developers.",
    //     ],
    // },
    // {
    //     title: "Web Developer",
    //     company_name: "Shopify",
    //     icon: shopify,
    //     iconBg: "#b7e4c7",
    //     date: "Jan 2022 - Jan 2023",
    //     points: [
    //         "Developing and maintaining web applications using React.js and other related technologies.",
    //         "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
    //         "Implementing responsive design and ensuring cross-browser compatibility.",
    //         "Participating in code reviews and providing constructive feedback to other developers.",
    //     ],
    // },
    // {
    //     title: "Full stack Developer",
    //     company_name: "Meta",
    //     icon: meta,
    //     iconBg: "#a2d2ff",
    //     date: "Jan 2023 - Present",
    //     points: [
    //         "Developing and maintaining web applications using React.js and other related technologies.",
    //         "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
    //         "Implementing responsive design and ensuring cross-browser compatibility.",
    //         "Participating in code reviews and providing constructive feedback to other developers.",
    //     ],
    // },
];

export const socialLinks = [
    {
        name: 'Contact',
        iconUrl: contact,
        link: 'tel:9589366643',
    },
    {
        name: 'GitHub',
        iconUrl: github,
        link: 'https://github.com/PranshuBasak',
    },
    {
        name: 'LinkedIn',
        iconUrl: linkedin,
        link: 'https://www.linkedin.com/in/pranshubasak/',
    },
    {
        name: 'Codedamn',
        iconUrl: codedamn,
        link: 'https://codedamn.com/user/pranshubasak',
    },
];

export const projects = [
    // {
    //     iconUrl: pricewise,
    //     theme: 'btn-back-red',
    //     name: 'Amazon Price Tracker',
    //     description: 'Developed a web application that tracks and notifies users of price changes for products on Amazon, helping users find the best deals.',
    //     // link: 'https://github.com/adrianhajdin/pricewise',
    // },
    // {
    //     iconUrl: threads,
    //     theme: 'btn-back-green',
    //     name: 'Full Stack Threads Clone',
    //     description: 'Created a full-stack replica of the popular discussion platform "Threads," enabling users to post and engage in threaded conversations.',
    //     // link: 'https://github.com/adrianhajdin/threads',
    // },
    // {
    //     iconUrl: car,
    //     theme: 'btn-back-blue',
    //     name: 'Car Finding App',
    //     description: 'Designed and built a mobile app for finding and comparing cars on the market, streamlining the car-buying process.',
    //     // link: 'https://github.com/adrianhajdin/project_next13_car_showcase',
    // },
    // {

    // {
    //     iconUrl: estate,
    //     theme: 'btn-back-black',
    //     name: 'Real-Estate Application',
    //     description: 'Developed a web application for real estate listings, facilitating property searches and connecting buyers with sellers.',
    //     // link: 'https://github.com/adrianhajdin/projects_realestate',
    // },
    // {
    //     iconUrl: summiz,
    //     theme: 'btn-back-yellow',
    //     name: 'AI Summarizer Application',
    //     description: 'App that leverages AI to automatically generate concise & informative summaries from lengthy text content, or blogs.',
    //     // link: 'https://github.com/adrianhajdin/project_ai_summarizer',
    // },
    
    {
        iconUrl: editmagicicon,
        theme: 'btn-back-blue',
        name: 'Editmagic AI',
        image: editmagicai,
        description: ' Developed EditMagic AI, an AI-powered image editing platform leveraging cloud-based AI APIs from Cloudinary. Integrating a credit system via Stripe for secure feature usage, and implemented using Next.js, Shadcn UI Components, Clerk, Stripe, MongoDB, Cloudinary, and Webhooks. Advanced image editing features such as Image Restore, Generative Fill, Object Remove, Object Recolor, and Background Remove',
        link: 'https://editmagic-ai.vercel.app/',
        git: "https://github.com/PranshuBasak/editmagic_ai.git",
    },
    {
        iconUrl: promptnest,
        theme: 'btn-back-green',
        name: 'PromptNest',
        image: promptnestImg,
        description: 'Developed utilizing the robust capabilities of Next.js 14, React.js, and a Mongoose-MongoDB backend, PromptNest is engineered to facilitate seamless CRUD operations. It integrates Next-Auth for secure authentication workflows and leverages Tailwind CSS for a responsive and modern user interface.',
        link: 'https://prompnest.vercel.app/',
        git: "",
    },
    {
        iconUrl: promptnest,
        theme: 'btn-back-green',
        name: 'EventHarbour',
        image: promptnestImg,
        description: 'Coming Soon...',
        link: 'https://eventharbours.vercel.app/',
        git: "",
    },
    {
        iconUrl: promptnest,
        theme: 'btn-back-green',
        name: 'FlexiConvert',
        image: promptnestImg,
        description: 'Comming Soon...',
        link: 'https://prompnest.vercel.app/',
        git: "",
    },
    {   iconUrl: snapgram,
        theme: 'btn-back-pink',
        name: 'Full Stack Instagram Clone',
        image: flavourful,
        description: 'SnapGram is a cutting-edge social media platform, combining React.js, Appwrite, React Query, TypeScript, Shadcn, and Tailwind CSS for an exceptional user experience. With robust authentication, Explore pages, Like and Save functionality, detailed post views, user profiles, browsing other users, easy post creation and editing, a responsive UI with React Query optimization, and Appwrite backend integration, SnapGram offers a seamless and engaging social networking experience. Its modular code architecture ensures scalability, maintainability, and code reusability, making SnapGram a standout in the world of social media apps.',
        link: 'https://flavour-ful.vercel.app/',
        git: "",
    },
    {   
        iconUrl: animeXplorer,
        theme: 'btn-back-red',
        name: 'AnimeXplorer',
        image: animeImage,
        description: 'Developed a dynamic single-page app that showcases Next 14 Server Side App with Server Actions, Infinite Scroll, and Framer Motion Animations.',
        link: '',
        git: "https://github.com/PranshuBasak/animxplorer.git",
    },
];